name: Keep Supabase Alive
permissions:
  contents: read
on:
  schedule:
    - cron: '0 12 */5 * *'  # Every 5 days

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://lhjtvfvlykasoiyfhznm.supabase.co
